#%%
from diffusers import AutoPipelineForText2Image
import torch
from dotenv import load_dotenv
import os
from IPython.display import display
import time


def get_new_path():
    # files are stored as image_1.webp, image_2.webp, etc.
    files = os.listdir()
    files = [f for f in files if f.endswith(".webp")]
    files = sorted(files)
    if len(files) == 0:
        return "image_1.webp"
    else:
        # get largest file
        file_nums = []
        for f in files:
            last_file = f
            last_file = last_file.split(".")[0]
            last_file = last_file.split("_")[-1]
            file_nums.append(int(last_file))
        last_file = max(file_nums)
        print(f"last index: {last_file}")
        return f"image_{last_file + 1}.webp"

#%%

# Load the .env file if it exists
load_dotenv()

# clear cuda cache
torch.cuda.empty_cache()

pipeline = AutoPipelineForText2Image.from_pretrained(
    "black-forest-labs/FLUX.1-dev", torch_dtype=torch.bfloat16
).to("cuda")
# pipeline.enable_model_cpu_offload()
# pipeline.load_lora_weights("sayakpaul/yarn_art_lora_flux", weight_name="pytorch_lora_weights.safetensors")

# %%



pipeline.load_lora_weights(
    "rafaelha/test_lora", weight_name="rafa_lora_v1_000002400.safetensors",
    # "j_lora_v1_000002000.safetensors",
    cross_attention_kwargs={"scale": 1.0},
)

#%%

# prompt = "TOK, a man in his 30th, as an astronaut floating in front of the ISS"
prompt = "Corporate Leader: A male named TOK, Caucasian, with neatly combed dark hair and clean-shaven, wearing a dark suit with a blue tie. He is standing confidently with arms crossed, against a sleek glass office backdrop."
prompt = "Go pro close up view of TOK skydiving by herself with a parachute over Berlin, her hands and legs are spread out, and she is smiling."
# prompt = "TOK, a create startup founder is standing in front of blackboard with lots of physics equations. He is 30, clean shaven, has razor thin shaved sides (haircuit), wears a manbun and wears a casual white dess shirt."
# prompt = "Studio Portrait with a Soft Smile: A full upper body shot of TOK, a woman with long, wavy blonde hair and blue eyes, standing in a professional studio setting. Her hair falls softly over her shoulders, and she is smiling gently at the camera. She is wearing a gray coat. Blurry scene of office in the background."
prompt = "TOK, a 29-year-old woman with long, flowing blonde hair, is mid-air during an exhilarating skydive. She wears a sleek black jumpsuit with bright orange accents and has her arms spread wide, catching the wind as she plummets through the sky. Her expression is one of pure thrill, eyes wide with excitement. The backdrop behind her is a sprawling landscape of mountains and fields, with a clear blue sky dotted with a few fluffy white clouds. The wind lifts her hair, creating an almost halo-like effect around her head."
# prompt = "In this image, TOK is captured just after leaping from a plane, her body in freefall against the backdrop of a breathtaking sunset. Her long blonde hair streams behind her in the wind as she wears a blue and white jumpsuit with a skydiving harness securely strapped across her torso. The sky is painted with warm hues of orange, pink, and purple, contrasting the tiny cityscape far below. TOK’s face shows a mix of concentration and exhilaration as she prepares to pull the parachute cord."
# prompt = "TOK, a young woman with long blonde hair, is seen mid-skydive, free-falling over a vast ocean below. She wears a red jumpsuit and a pair of yellow goggles. Her face is lit up with joy, her mouth slightly open in a scream of excitement. Her hair is whipped upward by the force of the wind, framing her face as the deep blue ocean glistens beneath her. Above her, the sky is bright and cloudless, with the plane she jumped from just barely visible in the background."
# prompt = "A close-up view of TOK during her skydive, highlighting her intense focus. Her long blonde hair is tied back in a loose braid, fluttering behind her as she falls. She’s dressed in a white and teal jumpsuit, with a helmet clipped to her side. The background shows a bird’s-eye view of a patchwork of farmland, rivers, and forests far below. The image captures the adrenaline in her expression, with her lips pulled back in a wide smile, and the rush of air distorting her cheeks slightly."
# prompt = "TOK, a 29-year-old woman with long blonde hair, has just deployed her parachute and is gracefully gliding down from the sky. She wears a bright green jumpsuit with a multicolored parachute billowing above her. Her hair cascades over her shoulders, gently swaying as the wind calms now that she’s slowed her descent. Below her is a picturesque valley, with rolling hills, trees, and a sparkling river winding through it. Her expression is peaceful yet full of exhilaration, as she enjoys the serene final moments of her jump."

prompts = [
    # "TOK, a 29-year-old woman with long, straight blonde hair, is standing confidently against a plain white background, dressed in a business casual outfit. She wears a light blue blouse tucked into tailored black pants, with a black blazer draped over her shoulders. Her hair falls naturally around her shoulders, framing her face, and she offers a warm, approachable smile. Her posture is professional yet relaxed, with her hands resting at her sides.",
    # "In this professional headshot, TOK is positioned in front of a soft grey background. She has long blonde hair styled in loose waves and wears a fitted white button-up shirt beneath a dark grey cardigan. Her expression is confident yet inviting, with her arms gently crossed in front of her chest. The lighting highlights her facial features, giving her a polished and business-like appearance, suitable for corporate settings.",
    # "TOK, with her long blonde hair neatly pulled back into a low ponytail, is dressed in a sleek business casual outfit. She wears a soft pink blouse with a thin silver necklace, and a charcoal blazer over it. The backdrop is a simple, muted color to keep the focus on her. Her bright eyes and genuine smile make her appear both professional and approachable. Her body is angled slightly to the side, with her hands lightly clasped in front of her.",
    # "This image shows TOK, a young woman with long blonde hair, standing in front of a modern office backdrop. She wears a navy blue blazer over a white blouse and has a pair of minimalist earrings visible. Her hair is parted to the side and styled in gentle waves. She is smiling softly, exuding confidence and professionalism, with her hands resting casually at her sides, showcasing her full upper body.",
    # "TOK, a 29-year-old professional, is photographed from the waist up, wearing a burgundy blouse tucked into beige trousers. She has long blonde hair that cascades over her shoulders in soft curls. Her expression is one of calm assurance, with a slight smile and confident posture. The background is blurred, showing hints of a bright office environment, adding to the business-like but approachable tone of the headshot.",
    # "In this professional headshot, TOK stands with a neutral-colored background. Her long blonde hair is styled in a sleek straight look, and she wears a dark green blouse with a black blazer. Her posture is upright, shoulders back, with her arms crossed in front of her chest, exuding confidence and professionalism. Her expression is poised, with a small smile that conveys warmth and approachability.",
    # "TOK, a 29-year-old woman with long blonde hair, is dressed in a light grey blazer over a black top for this business casual headshot. Her hair is parted down the middle and styled in soft waves, giving her a polished look. She stands with her arms at her sides and her posture is relaxed yet confident. The background is a soft gradient, subtly transitioning from light to dark, adding depth to the image.",
    #>> "In this full upper-body shot, TOK is dressed in a business casual outfit consisting of a blue blouse tucked into a high-waisted black skirt. Her long blonde hair is pinned back on one side, revealing delicate earrings. She stands against a modern glassy office backdrop with a view, with her arms loosely crossed in front of her. Her smile is professional yet friendly, and her body language exudes confidence.",
    # "In this full upper-body shot, TOK is dressed in a business casual outfit consisting of a blue blouse tucked into a high-waisted black skirt. Her long blonde hair is pinned back on one side, revealing delicate earrings. She stands against office backdrop with a view of the ocean, with her arms loosely crossed in front of her. Her smile is professional yet friendly, and her body language exudes confidence.",
    # "TOK is posed against a soft blue background in a professional headshot. She has long blonde hair styled in loose waves and wears a pale peach blouse under a fitted grey blazer. Her posture is confident but relaxed, and her smile is open and approachable. She stands with her arms slightly folded in front of her, presenting a calm, business-like demeanor.",
    # "In this professional headshot, TOK, a 29-year-old woman with long blonde hair, is dressed in a crisp white blouse paired with a navy blazer. Her hair is styled in soft waves, and her posture is slightly angled to the left, with her arms lightly clasped at her waist. The backdrop is a neutral soft beige, helping her warm, confident smile stand out, creating an image that feels both polished and approachable.",
    # "In this full upper-body shot, TOK is dressed in a business casual outfit consisting of a blue blouse tucked into a high-waisted black skirt. Her blonde hair is in a modern up-do, revealing delicate earrings. She stands against a modern glassy office backdrop with a view, with her arms loosely crossed in front of her. Her smile is professional yet friendly, and her body language exudes confidence.",
    # "TOK, a 29-year old female astronaut. She has long blonde hair, and is wearing a white space suit with the helmet off. She is looking at the camera with a smile, and the Earth is visible in the background.",
    # "TOK, Holding a giant USA flag jubilant over her head after just having won the swimming competition. "
    # "TOK, a 29-year-old woman with long blonde hair, crouches behind dense foliage in a misty forest, wearing a camouflage jacket. Her face is focused and alert, her eyes scanning the surroundings. Her hair is pulled back into a tight ponytail, and a soft light from the early morning sun highlights her determined expression. In her hands, she holds a hunting bow, ready to take aim.",
    # "Beneath the surface of a crystal-clear ocean, TOK is scuba diving among vibrant coral reefs. Her long blonde hair is tucked under a sleek black diving mask, but her face is fully visible through the transparent visor. She is surrounded by colorful fish and sea life, her eyes wide with amazement as she explores the underwater world. Bubbles rise around her, adding to the sense of adventure.",
    # "TOK, with her long blonde hair tied into a practical bun, is scaling a steep mountain cliff at dawn. She wears a red climbing jacket with a harness and ropes around her waist. The golden sunrise casts a warm glow on her face, highlighting her determined expression. Her focus is entirely on reaching the summit as she grips the rock with confidence.",
    # "In a futuristic space setting, TOK stands on the surface of the moon in a full astronaut suit. Her face is clearly visible through the helmet visor, illuminated by the distant Earth in the background. Her long blonde hair is neatly tied back inside the helmet, and her expression is one of awe as she gazes at the barren lunar landscape, her hand raised in a thumbs-up.",
    # "TOK is paragliding high above a vast canyon, her long blonde hair blowing in the wind behind her. She wears a blue windbreaker and has protective goggles perched on her forehead. Her face shows pure excitement, with a wide smile as she navigates the open air, gliding gracefully over the breathtaking landscape below.",
    # "TOK, a 29-year-old woman with long blonde hair tied in a high ponytail, is riding a massive wave on her surfboard. She’s wearing a black wetsuit, and her face is filled with focus and determination as she expertly balances on the board. The powerful wave curls behind her, but her eyes are fixed ahead, completely in the moment.",
    # "Inside the cockpit of a helicopter, TOK is the pilot, confidently steering the controls. Her long blonde hair is braided neatly over her shoulder, and she wears aviator sunglasses perched on her head. Her face is visible through the clear windshield, displaying a calm and focused expression as she navigates the aircraft through clear skies over a dense forest.",
    # "TOK stands in the basket of a hot air balloon, gently rising into the sky as the sun sets behind her. She wears a cozy sweater, and her long blonde hair is loose, gently blowing in the wind. Her face is lit by the warm orange glow of the sunset, with a serene and peaceful smile as she looks out over the vast landscape below.",
    # "TOK is captured mid-skydive, her long blonde hair pulled into a high ponytail, with a bright pink jumpsuit. She is free-falling from a high altitude, the open sky around her and the ground far below. Her face is visible through her clear goggles, showing a mix of exhilaration and joy as she plummets toward the Earth.",
    # "TOK is captured mid-bungee jump, her long blonde hair flying in every direction as she plunges from a high bridge. She wears a light jacket, and her face is fully visible, reflecting a blend of adrenaline and thrill. The ropes attached to her ankles stretch taut above her, and the river far below comes into view, adding to the excitement of the scene.",
    # "TOK is riding a galloping horse across a desert, her long blonde hair tied back in a flowing ponytail. She wears a rugged leather jacket, and her face is clearly visible, showing concentration and joy as the wind whips past her. The vast, sandy landscape stretches out behind her as the sun begins to set, casting a golden hue on the scene.",
    # "TOK is snowboarding down a steep, snowy mountain slope, her long blonde hair tucked inside a helmet but visible through the transparent visor. She wears a white and blue snow jacket, and her face is filled with concentration as she expertly maneuvers through the snow. The cold air reddens her cheeks slightly, but her expression is determined and focused.",
    # "Inside a dimly lit cave, TOK is exploring with a bright torch in her hand. Her long blonde hair is tied back in a messy bun, and she wears a rugged outfit suitable for adventuring underground. Her face is illuminated by the torchlight, showing a look of curiosity and excitement as she gazes at ancient rock formations.",
    # "TOK is zip-lining through a lush jungle, her long blonde hair streaming behind her in the wind. She wears a green adventure vest, and her face is visible through the clear visor of her helmet, showing a wide smile as she zooms through the dense treetops. The vibrant greenery surrounds her, creating a thrilling and adventurous scene.",
    # "TOK is paddling through rough rapids in a whitewater raft, her long blonde hair damp and tied into a low ponytail. She wears a red life vest, and her face is a mixture of focus and excitement as she braces herself against the powerful water. Her eyes are wide with adrenaline, and her expression shows sheer determination to navigate the river safely.",
    # "In the heart of a dense jungle, TOK is trekking through thick foliage, her long blonde hair pulled back into a high ponytail. She wears a light green shirt with hiking boots, and her face is visible, showing concentration as she uses a machete to clear a path. The sun filters through the canopy above, casting dappled light on her determined expression.",
    # "TOK is sitting by a crackling campfire under a star-filled sky, her long blonde hair falling loosely over her shoulders. She wears a cozy flannel shirt, and her face is lit by the warm glow of the fire. She gazes up at the stars with a peaceful smile, her expression reflecting a deep connection with nature and the serenity of the moment.",
    # "TOK is leading a camel through a vast desert, her long blonde hair tied up in a practical bun to keep cool in the hot sun. She wears a light-colored desert outfit, and her face is clearly visible, showing calm determination as she guides the animal through the sand dunes. The sun casts long shadows, creating a striking contrast in the barren landscape.",
    # "On the deck of a fishing boat, TOK is holding a large fishing rod, her long blonde hair blowing in the ocean breeze. She wears a waterproof jacket and a baseball cap, and her face shows a confident smile as she reels in a catch. The vast blue ocean stretches out behind her, with seagulls circling overhead, adding to the sense of adventure.",
    # "TOK is standing at the edge of a dormant volcano, looking out over the massive crater. Her long blonde hair is tied back into a neat braid, and she wears a sturdy hiking jacket. Her face is lit with awe and curiosity as she takes in the breathtaking view. The rugged, volcanic terrain stretches out before her, creating an adventurous and dramatic backdrop.",
    # "TOK, a 29-year-old woman with long blonde hair, is sitting comfortably inside a gigantic avocado half, like a cozy chair. Her business casual outfit contrasts with the vibrant green of the avocado. She leans back against the smooth surface, her legs crossed, with a curious smile on her face. The pit of the avocado rests beside her, adding to the surreal, playful atmosphere.",
    # "TOK is joyfully sliding down the bristles of a massive paintbrush as if it were a playground slide. Her long blonde hair streams behind her, and her expression is one of pure excitement. The brush leaves a colorful trail of paint behind her, creating a rainbow of colors that spreads across the canvas-like background.",
    # "In a vibrant, abstract scene, TOK is swimming through a pool of thick, swirling paint. Her long blonde hair is slicked back, and her face shows a playful grin as she cuts through the waves of colorful paint, which seem to ripple like water. The colors blend around her, creating a mesmerizing, fluid effect.",
    # "A miniature version of TOK is standing inside a delicate porcelain teacup, surrounded by a pool of tea. Her long blonde hair is styled neatly, and she wears a small version of her business casual outfit. She looks up with wonder at the giant spoon resting beside her, as steam rises gently from the tea.",
    # "TOK, now smaller than a flower, is swinging playfully from the petal of an oversized daisy. Her long blonde hair flows in the wind, and her expression is carefree as she enjoys the ride. The background is filled with towering, colorful flowers, creating a dreamy and magical garden scene.",
    # "TOK is gracefully dancing across an enormous sheet of paper, leaving swirling pencil sketches and doodles in her wake. Her long blonde hair flows around her as she twirls, and her face is filled with creative energy. The pencil in her hand appears to be sketching behind her as she moves, bringing art to life on the page.",
    # "In a surreal artistic world, TOK is balancing on the edge of a massive painter’s palette. Her feet rest on vibrant blobs of paint, and her arms are outstretched to maintain her balance. Her face shows concentration, but her playful smile suggests she's enjoying this creative challenge. The background is filled with oversized paintbrushes and splashes of color.",
    # "TOK is flying through the sky on a giant pencil as if it were a broomstick. Her long blonde hair whips behind her as she speeds through a surreal, cloudy world where other writing tools float in the air. Her face beams with excitement, and below her, the world is drawn like a sketched landscape.",
    # "In a dreamlike beach setting, TOK is sitting comfortably inside an oversized, iridescent seashell. Her long blonde hair flows gently as she leans back, resting her arms on the smooth, pearlescent surface. The ocean waves lap at the edges of the shell, creating a serene and magical atmosphere.",
    # "TOK is riding a giant open book like a surfboard, gliding over an ocean made of swirling words and letters. Her long blonde hair flows behind her as she balances expertly on the pages, which curl like waves beneath her. Her face shows pure joy, as if she’s riding the waves of a story come to life.",
    # "In a whimsical, musical world, a miniature version of TOK is standing on the lines of a giant music staff. Giant musical notes float around her, and she reaches out to touch one with a sense of wonder. Her long blonde hair is tied back, and her expression reflects her fascination with the strange, melodic world she finds herself in.",
    # "TOK is walking gracefully across a glowing ribbon of light suspended in the air. Her long blonde hair shimmers with the glow of the light beneath her feet, and her face is calm, almost meditative, as she takes careful steps. The background is a surreal, abstract space filled with floating orbs and shifting colors.",
    # "In a magical, surreal setting, TOK is sitting on the ground, blowing giant bubbles made of shimmering glass. Her long blonde hair falls gently over her shoulders, and her face is filled with delight as the delicate bubbles float away, catching the light and reflecting the vibrant, colorful world around her.",
    # "TOK, in miniature form, is climbing a towering stack of books, her long blonde hair flowing behind her. Each book is larger than life, and her expression is one of determination and curiosity as she scales the spines, reaching toward a massive, glowing light at the top of the stack.",
    # "In a surreal, dreamlike setting, TOK stands atop a giant, ticking pocket watch. Her long blonde hair cascades down her back as she gazes at the oversized clock hands moving slowly beneath her feet. The background is filled with floating, disjointed timepieces, creating a sense of being inside a world where time has its own rules.",
    # "TOK is sitting on a fluffy, oversized cloud of cotton candy that floats gently through the air. Her long blonde hair is softly tousled by the wind, and her face is lit with a playful smile as she reaches down to scoop a piece of the sugary cloud. The sky around her is painted with pastel pinks and blues, creating a dreamlike, sweet atmosphere.",
    # "In an ethereal world, TOK is standing on an invisible platform high above the ground, holding a giant paintbrush. Her long blonde hair flows around her, and her face is focused and serene as she paints colorful streaks directly onto the sky, creating a vibrant sunset. The horizon below fades into clouds, blending with the hues she creates.",
    # "TOK is playfully swinging from the hand of a giant clock, her long blonde hair flowing wildly as she moves. She’s wearing a casual outfit, and her face shows a mixture of exhilaration and fun. The massive clock floats in a surreal landscape of swirling clouds and abstract shapes, giving the scene a sense of time bending.",
    # "In a surreal, playful scene, a tiny version of TOK is diving into a giant cup of coffee, mid-air above the swirling liquid. Her long blonde hair is tied back, and her face shows a mix of excitement and anticipation. Below her, the coffee swirls with patterns of cream, creating a mesmerizing visual effect.",
    # "TOK is standing on the handle of a giant paintbrush, using the bristles like the sail of a boat as she navigates through an ocean of swirling black ink. Her long blonde hair is tied into a neat bun, and her expression is focused but serene as she guides the paintbrush through the inky waves. The scene is filled with abstract patterns and splashes of color emerging from the ink.",
    "TOK standing in a neon-lit cyberpunk alley – TOK leans against a gritty, rain-soaked alley wall in a sprawling cyberpunk metropolis, his brown eyes glowing with reflections from neon signs that advertise holographic ads. His face is partially illuminated by the pink and blue neon lights, casting sharp shadows on his features. Rain drips from the edges of his leather jacket, and his man bun is slightly damp as he scans the crowded, futuristic streets for danger.",
    "TOK as a hacker in a virtual reality chamber – Sitting in a dimly lit room filled with floating holographic screens, TOK’s face is illuminated by the green and blue light of code cascading down in front of him. His expression is focused and intense as his brown eyes dart between multiple streams of data. Wires are connected to his hands, allowing him to manipulate the virtual world, and his man bun is tightly tied as he navigates through a maze of digital information.",
    "TOK riding a futuristic motorcycle through a cyberpunk city at night – TOK’s face is clearly visible as he speeds through the rain-soaked streets of a towering cyberpunk city on a sleek, glowing motorcycle. His brown eyes are narrowed in concentration, and the city’s neon lights reflect off his visor. The sharp lines of towering skyscrapers and billboards advertising robotic enhancements blur past him, but his face remains the focus, illuminated by the vibrant colors of the city.",
    "TOK facing off against a group of cyber-enhanced mercenaries in a dark alley – In a tense standoff, TOK’s face is set in determination as he confronts a group of heavily cyber-enhanced mercenaries. The neon lights from nearby billboards flicker on his features, highlighting his calm yet fierce expression. His brown eyes reflect the glowing implants in the mercenaries’ faces, but TOK remains unfazed, his hands ready to unleash his own hidden tech.",
    "TOK in a cyberpunk nightclub surrounded by holographic dancers – TOK’s face is lit up by pulsating neon lights as he stands in the center of a crowded cyberpunk nightclub. His brown eyes are sharp as he scans the room, surrounded by holographic dancers and patrons with cybernetic enhancements. The holograms reflect off his features, and his expression is one of quiet intensity as he navigates through the flashing lights and vibrant energy of the futuristic club.",
    "TOK, the giant among dwarfs – TOK stands towering over a bustling village of dwarfs, who are no taller than his knees. His man bun is neatly tied, his brown eyes glistening in the sunlight as he bends down to greet the small, bearded villagers. One dwarf tugs on TOK's pants, while others present him with tiny tools as gifts. The scene shows TOK's face clearly as he smiles, the dwarfs staring up in awe.",
    "TOK in a world made entirely of paper – TOK’s face reflects a mix of wonder and curiosity as he moves through a city made of intricate origami. The light filters through the paper buildings, creating delicate shadows across his features. Paper people greet him, folding themselves into different shapes, while paper birds soar above. TOK’s expressive face stands out amid the delicate surroundings, his hands lightly touching a paper flower.",
    "TOK surfing on an open book over a sea of letters – TOK’s intense focus is captured as he surfs on the pages of a massive open book, gliding across a sea of swirling letters. His face is full of determination, eyes sharp, hair tied back in a man bun that flutters in the wind. Below, letters rise and fall like waves, and his face is illuminated by the surreal light from the floating words.",
    "TOK riding a dinosaur in a prehistoric jungle – TOK sits proudly on a Triceratops, his brown eyes scanning the thick prehistoric jungle ahead. His face reflects a combination of excitement and adventure as he grips the reins made of vines. Sunlight filters through the ancient ferns, highlighting his features as he leads the dinosaur through the wild terrain, a volcano smoldering in the distance.",
    "TOK walking through a forest of giant glowing mushrooms – The vibrant glow from the massive mushrooms casts a soft light on TOK’s face, emphasizing his curious expression. His brown eyes shine as he reaches out to touch one of the luminescent mushroom caps. Tiny glowing creatures flutter around him, illuminating his features against the surreal forest backdrop.",
    "TOK at a tea party with the Mad Hatter – Sitting at a chaotic table filled with floating teapots and mismatched chairs, TOK’s face is fully visible as he listens intently to the Mad Hatter’s animated conversation. His expression is both amused and intrigued, his eyes focused on the eccentric characters around him. A teacup floats mid-air near his face, adding to the whimsical atmosphere.",
    "TOK in a floating city made of clouds – TOK’s face is serene as he walks along a soft, misty path in a city built on clouds. The pastel-hued sky reflects in his brown eyes, his man bun slightly tousled by the breeze. His expression is peaceful, his gaze set on the beautiful buildings made of shimmering clouds and mist. Winged creatures fly overhead, but the focus remains on TOK’s calm, thoughtful face.",
    "TOK piloting a steam-powered airship over a Victorian city – TOK stands at the helm of a brass-covered airship, his face clearly visible as he steers the massive vessel through the skies. His expression is determined and focused, eyes glinting as the wind whips through his man bun. Behind him, Victorian rooftops stretch out below, but TOK’s confident face is the centerpiece, highlighted by the warm glow of the setting sun.",
    "TOK in a world where everything is made of crystal – TOK’s face reflects the dazzling light as he walks through a world of shimmering crystal. Every tree, flower, and structure is made of faceted glass-like crystal, refracting light onto his features. His brown eyes sparkle as he inspects a crystal bird that flutters nearby, his face glowing with wonder in this crystalline landscape.",
    "TOK exploring a city made of gears and machinery – TOK’s face is illuminated by the warm glow of molten metal as he walks through a city of giant gears and steam-powered machines. His features show intense curiosity as he studies the intricate mechanical world around him, steam rising from the ground. His brown eyes focus on a massive turning gear, and the warm light highlights his expression of fascination.",
    "TOK in a world where time is frozen – TOK stands in a city where everything, from falling rain to fluttering birds, is frozen in time. His face, filled with awe, is clearly visible as he examines a droplet of water suspended in mid-air. His brown eyes reflect the frozen world around him, his man bun neat and tidy as he contemplates the eeriness of a moment caught in stasis.",
    "TOK riding a mechanical horse in a futuristic desert – TOK’s face is stern and determined as he rides a sleek, metallic horse through a futuristic desert. The sun casts a harsh glow on his features, and his brown eyes squint slightly in the bright light. The horse’s mechanical joints gleam, and TOK’s expression is one of focused control as he speeds through the dystopian landscape.",
    "TOK stepping through a portal into a world of floating islands – TOK’s face is illuminated by the bright light of a swirling portal as he steps into a world of floating islands in the sky. His eyes widen with surprise and excitement as he takes in the sight of massive islands suspended in mid-air, connected by glowing bridges. His expression of wonder is the focus of the scene as the surreal landscape unfolds around him.",
    "TOK playing chess with a living statue – Sitting across from a marble statue that moves on its own, TOK’s face is captured in deep concentration. His brown eyes focus intensely on the chessboard between them, his fingers hovering over a piece. The statue’s stone features contrast with TOK’s expressive face, which shows a mix of strategic thinking and excitement as the game unfolds.",
    "TOK standing at the edge of a glowing abyss – TOK’s face is lit by the eerie glow of an abyss that stretches endlessly beneath him. His expression is one of awe and trepidation as he peers over the edge, his brown eyes reflecting the swirling lights from below. The vast expanse of glowing mist seems to pull at him, but his focused face remains the highlight of the scene.",
    "TOK in a world where gravity is reversed – With a smile of sheer amazement, TOK floats upside down in a world where gravity no longer holds sway. His man bun floats above his head, and his brown eyes sparkle as he glances down—or up—at the city streets that now exist in the sky. Objects and people float around him, but the focus is on TOK’s delighted, upturned face.",
    "TOK battling a giant sandworm in a desert – In the heat of battle, TOK’s face shows determination and grit as he faces down a massive sandworm emerging from the dunes. Sweat glistens on his forehead, and his brown eyes are locked on the creature as it rises above him. The scene is dynamic, but TOK’s intense expression remains the focal point as he prepares to strike.",
    "TOK in a mirror maze where his reflections come to life – Surrounded by reflections that move independently, TOK’s face is full of wonder and slight confusion. His brown eyes dart from one reflection to another, each of which shows a slightly different expression. The maze of mirrors distorts the scene, but TOK’s real face remains in clear focus, the others mimicking his expressions eerily.",
    "TOK walking through an underwater city – As TOK walks along a street submerged beneath the ocean, his face shows amazement. His hair floats slightly in the water, and his brown eyes follow a school of fish swimming past. The buildings around him are coral-encrusted, but the soft blue light of the ocean illuminates TOK’s curious and calm expression.",
    "TOK in a world made of giant clockwork mechanisms – Surrounded by enormous, ticking gears and swinging pendulums, TOK’s face is a mixture of awe and fascination. His brown eyes carefully follow the movements of the clockwork around him as he steps cautiously through the intricate mechanisms. The warm, golden light reflects off the metal, highlighting the wonder in TOK’s expression.",
    "TOK in a candy-coated fantasy world – Standing in a land of giant candy canes and flowing rivers of chocolate, TOK’s face is a mixture of amusement and disbelief. His eyes sparkle as he reaches out to touch a towering gumdrop tree, his features glowing with the bright colors of the sweet landscape around him.",
    "TOK in a library where the books are alive – TOK’s face is lit by the glow of floating, illuminated books that flutter around him like birds. His expression is one of deep curiosity, his brown eyes following the path of a book as it opens mid-air to reveal glowing text. The soft light from the pages casts gentle shadows on his features.",
    "TOK entering a labyrinth made of light – TOK stands at the entrance of a glowing labyrinth made entirely of beams of light. His face is determined and focused, his brown eyes reflecting the intricate patterns of light before him. As he steps forward, the light shifts around his face, creating an ethereal glow.",
    "TOK playing a magical harp in an enchanted forest – Sitting in a clearing surrounded by ancient, glowing trees, TOK’s face is peaceful as he plays a harp that shimmers with magic. His eyes are closed, and his expression is serene, completely absorbed in the music. The soft glow from the harp strings illuminates his face as the forest responds to the music.",
    "TOK sailing through the stars on a celestial ship – On a ship that sails through the starry expanse of space, TOK’s face is lit by the distant glow of galaxies and nebulae. His brown eyes gaze out into the infinite, filled with wonder and determination as he steers the ship through constellations and glowing star systems.",
    "TOK leading an army of robotic animals in a futuristic city – In the midst of a high-tech city, TOK’s face is filled with determination as he commands an army of sleek, robotic animals. His brown eyes are sharp, focused on the battle ahead. The neon lights of the city reflect off his features as the robotic creatures respond to his every command.",
    "TOK exploring a desert planet with two suns – Standing on the arid surface of a distant desert planet, TOK’s face is illuminated by the twin suns setting on the horizon. His features show a mix of awe and curiosity as he looks across the endless dunes, the light casting long shadows across his face.",
    "TOK in a world where plants grow as skyscrapers – As TOK walks through a city where towering plants replace buildings, his face is filled with curiosity and wonder. His brown eyes trace the vines that wrap around the giant stalks, and sunlight filters through the enormous leaves, casting intricate shadows on his face.",
    "TOK riding a griffin over a vast canyon – Flying high above a massive canyon, TOK’s face is filled with exhilaration and joy. His brown eyes sparkle in the sunlight as he holds onto the reins of the griffin, the wind blowing through his hair as they soar through the sky.",
    "TOK stepping onto the moon in a futuristic spacesuit – TOK’s face is clearly visible through the helmet of his futuristic spacesuit as he steps onto the surface of the moon. His brown eyes widen in amazement as he looks out at the Earth hanging in the starry sky, his face reflecting the glow of distant planets and stars.",
]

seeds = [0]
for prompt in prompts:
    for s in seeds:
        start = time.perf_counter()
        images = pipeline(
            prompt,
            guidance_scale=3.0,
            height=1024,
            width=1024,
            num_images_per_prompt=1,
            num_inference_steps=32,
            generator= torch.Generator(device="cuda").manual_seed(936188 + s)
        ).images
        print(f"Time taken: {time.perf_counter() - start:.2f}s")

        for image in images:
            display(image)
            path = get_new_path()
            image.save(path)
